#
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20180809
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

# Constant
MODULE_NAME 		= std.stdio
MODULE_INTRODUCE 	= 输入输出标准库测试例子

# Compile
MODULE_LINK 	= c
# MODULE_BUILD 		= DEBUG
MODULE_TARGET 		= $(MODULE_NAME).app

include ../../mk/config.mk
include ${PROJECT_MAKEFILE_HOME}/global.mk
