#
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20190531
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

include ../../mk/config.mk

# Constant
MODULE_NAME 		= aqnote_a
MODULE_INTRODUCE 	= aqnote a测试模块

# Compile
MODULE_LINK 		= c
MODULE_BUILD 		= DEBUG
MODULE_TARGET 		= lib$(MODULE_NAME).a lib$(MODULE_NAME).so


include ${PROJECT_MAKEFILE_HOME}/global.mk
