#
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20190531
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

include ../../mk/config.mk

###############################
# Module Info
###############################
MODULE_NAME 		= aqnote_a
MODULE_INTRODUCE 	= aqnote a测试模块
MODULE_TARGET 		= lib$(MODULE_NAME).a lib$(MODULE_NAME).so

###############################
# Compile Options
###############################
MODULE_LINK 		= c
MODULE_BUILD 		= DEBUG
MODULE_TOOLCHAIN	= x86_64-linux-gnu

include ${PROJECT_MAKEFILE_HOME}/global.mk
