ifeq "" "${PROJECT_HOME}"
	PROJECT_HOME 			= ../..
	PROJECT_BUILD_HOME 		= ${PROJECT_HOME}/build
	PROJECT_APPS_HOME 		= ${PROJECT_HOME}/apps
	PROJECT_DOCS_HOME 		= ${PROJECT_HOME}/docs
	PROJECT_MODULES_HOME 	= ${PROJECT_HOME}/modules
endif