#
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20190324
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

# Constant
MODULE_NAME 		= std.sort
MODULE_INTRODUCE 	=

# Depends
MODULE_DEPENDS_PROJ 		=
MODULE_DEPENDS_PKG			=
MODULE_DEPENDS_NONSTD_PATH 	=
MODULE_DEPENDS_NONSTD_FILE	=

# Compile
MODULE_COMPILER 	= c
# MODULE_BUILD 		= DEBUG
MODULE_OUTPUT 		= $(MODULE_NAME).app

include ../../constant.makefile
include ${PROJECT_HOME}/global.makefile
