
include ../../makefile.d/config.makefile

# Constant
MODULE_NAME 		= moduleB
MODULE_INTRODUCE 	=

# Depends
DEPEND_MODULE 		=
DEPEND_PKG			=

# Compile
MODULE_LINK 	= cpp
MODULE_BUILD 	= DEBUG
MODULE_OUTPUT 	= lib$(MODULE_NAME).a lib$(MODULE_NAME).so

include ${PROJECT_MAKEFILE_HOME}/global.makefile