
MODULE_NAME = moduleB
MODULE_INTRODUCE =

MODULE_COMPILER = cpp
MODULE_OUTPUT = libmoduleB.a libmoduleB.so

LIBRARY_HOME := 
LIBRARY_FILE := 
LIBRARY_PKG  := 

include ../../constant.makefile
include ${PROJECT_HOME}/global.makefile