
include ../../mk/config.mk

# Constant
MODULE_NAME 		= moduleB
MODULE_INTRODUCE 	=

# Depends
DEPEND_MODULE_LIST 		=
DEPEND_PKG			=

# Compile
MODULE_LINK 	= cpp
MODULE_BUILD 	= DEBUG
MODULE_TARGET 	= lib$(MODULE_NAME).a lib$(MODULE_NAME).so

include ${PROJECT_MAKEFILE_HOME}/global.mk