# Constant
MODULE_NAME = aqnote_mma
MODULE_INTRODUCE =
MODULE_TARGET = lib$(MODULE_NAME).a lib$(MODULE_NAME).so

# Depends
DEPEND_MODULE_LIST 	=
DEPEND_PKG			=

## Compile
MODULE_LINK = cpp
#MODULE_BUILD 		= DEBUG

include ../../mk/config.mk
include ${PROJECT_MAKEFILE_HOME}/global.mk