#     Title: 
#    Author: "Peng Li"<aqnote@qq.com>
#     CDate: 20180809
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

SOURCE_DEBUG  	:= $(DEBUG)
SOURCE_TYPE 	:= c

LIBRARY_HOME 	:= 
LIBRARY_FILE 	:= 
LIBRARY_PKG  	:= gtk+-2.0

include ../../main.makefile
