
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20190325
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

# Constant
MODULE_NAME 		= thread.multithread
MODULE_INTRODUCE 	= 多线程数组管理

# Depends
DEPEND_MODULE 	=
DEPEND_NONSTD 	=
DEPEND_PKG		=
DEPEND_STD		= pthread

# Compile
MODULE_LINK 	=
MODULE_BUILD 		= DEBUG
MODULE_OUTPUT 		= $(MODULE_NAME).app

include ../../makefile.d/config.makefile
include ${PROJECT_MAKEFILE_HOME}/global.makefile
