
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20190325
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

# Constant
MODULE_NAME 		= gtk.lifecycle
MODULE_INTRODUCE 	=

# Depends
DEPEND_MODULE 		=
DEPEND_NONSTD 		=
DEPEND_PKG			= gtk+-2.0 gtk+-3.0

# Compile
MODULE_LINK 		= c
MODULE_BUILD 		= DEBUG
MODULE_OUTPUT 		= $(MODULE_NAME).app

include ../../makefile.d/config.makefile
include ${PROJECT_MAKEFILE_HOME}/global.makefile