#
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20180809
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

# Constant
MODULE_NAME 		= ffmpeg.0x01
MODULE_INTRODUCE 	= 调用ffmpeg拉取rtsp流

# Depends
DEPEND_MODULE_LIST 		= 
DEPEND_NONSTD 	=
DEPEND_PKG_CONFIG   = /opt/aqnote/ffmpeg/lib/pkgconfig
DEPEND_PKG			= libavutil libavdevice libavformat libavcodec libavfilter libswscale libswresample

# Compile
MODULE_LINK 	= c
# MODULE_BUILD 		= DEBUG
MODULE_TARGET 		= $(MODULE_NAME).app

include ../../mk/config.mk
include ${PROJECT_MAKEFILE_HOME}/global.mk
