#
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20180809
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

# Constant
MODULE_NAME 		= ffmpeg.0x01
MODULE_INTRODUCE 	= 调用ffmpeg拉取rtsp流

# Depends
MODULE_DEPENDS_PROJ 		= 
MODULE_DEPENDS_PKG_CONFIG   = /opt/aqnote/ffmpeg/lib/pkgconfig
MODULE_DEPENDS_PKG			= libavutil libavdevice libavformat libavcodec libavfilter libswscale libswresample
MODULE_DEPENDS_NONSTD_PATH 	=
MODULE_DEPENDS_NONSTD_FILE	=

# Compile
MODULE_COMPILER 	= c
# MODULE_BUILD 		= DEBUG
MODULE_OUTPUT 		= $(MODULE_NAME).app

include ../../constant.makefile
include ${PROJECT_HOME}/global.makefile
