
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20181210
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#
MODULE_NAME = gcc.assembly
MODULE_INTRODUCE =
MODULE_BUILD = DEBUG

MODULE_TARGET = main.app

# Depends
DEPEND_MODULE_LIST 		=
DEPEND_NONSTD 		=
DEPEND_PKG			=

assembly:
	$(CPP) $(CFLAGS) $(C_SOURCES) -S

include ../../mk/config.mk
include ${PROJECT_MAKEFILE_HOME}/global.mk
