
#     Title: 
#    Author: "Peng Li"<aqnote@qq.com>
#     CDate: 20181210
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#
MODULE_NAME = gcc.assembly
MODULE_INTRODUCE = 
MODULE_DEPENDS = 
MODULE_BUILD = DEBUG

MOUDLE_OUTPUT = main.app

LIBRARY_HOME := 
LIBRARY_FILE := 
LIBRARY_PKG  := 

include ../../constant.makefile
include ${PROJECT_HOME}/global.makefile

assembly:
	$(CPP) $(CFLAGS) $(C_SOURCES) -S