
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20181210
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#
MODULE_NAME = gcc.assembly
MODULE_INTRODUCE =
MODULE_BUILD = DEBUG

MODULE_OUTPUT = main.app

# Depends
DEPEND_MODULE 		=
DEPEND_NONSTD 		=
DEPEND_PKG			=

assembly:
	$(CPP) $(CFLAGS) $(C_SOURCES) -S

include ../../makefile.d/config.makefile
include ${PROJECT_MAKEFILE_HOME}/global.makefile
