
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20181210
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

# Constant
MODULE_NAME 		= framebuffer
MODULE_INTRODUCE 	=

# Compile
MODULE_LINK 	=
MODULE_BUILD 		= DEBUG
MODULE_OUTPUT 		= $(MODULE_NAME).app

include ../../makefile.d/config.makefile
include ${PROJECT_MAKEFILE_HOME}/global.makefile
