#     Title: common used Makefile
#    Author: "Peng Li"<aqnote@qq.com>
#     CDate: 20180809
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#


## defaug flag
APP_DEBUG = $(DEBUG)
APP_SOURCE := c

APP_LIBRARY_HOME :=
APP_LIBRARY_FILES := pthread
APP_LIBRARY_PKG  := 

include ../../core.mk