#
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20181210
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

include ../../mk/config.mk

# Constant
MODULE_NAME 		= multimodule
MODULE_INTRODUCE 	=
MODULE_TARGET 		= $(MODULE_NAME).app

# Depends
DEPEND_MODULE_LIST 			= AQNOTE_MMA AQNOTE_MMB
DEPEND_MODULE_AQNOTE_MMA_HOME 	= $(PROJECT_MODULES_HOME)/aqnote_mma
DEPEND_MODULE_AQNOTE_MMA_LIB	= aqnote_mma
DEPEND_MODULE_AQNOTE_MMB_HOME 	= $(PROJECT_MODULES_HOME)/aqnote_mmb
DEPEND_MODULE_AQNOTE_MMB_LIB	= aqnote_mmb

# Compile
MODULE_LINK 		= cpp
# MODULE_BUILD 		= DEBUG


include ${PROJECT_MAKEFILE_HOME}/global.mk
