
#     Title: 
#    Author: "Peng Li"<aqnote@qq.com>
#     CDate: 20181210
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#
SOURCE_DEBUG  	:= 1
SOURCE_TYPE 	:= c

LIBRARY_HOME 	:= 
LIBRARY_FILE 	:= pthread
LIBRARY_PKG  	:= 

include ../../main.makefile