#
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20180809
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

# Constant
MODULE_NAME 		= aqnote_algorithm
MODULE_INTRODUCE 	= aqnote的算法模块，包含基本算法

# Compile
MODULE_COMPILER 	= c
MODULE_BUILD 		= DEBUG
MODULE_OUTPUT 		= lib$(MODULE_NAME).a lib$(MODULE_NAME).so

include ../../constant.makefile
include ${PROJECT_HOME}/global.makefile
