#
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20180809
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

include ../../mk/config.mk

# Constant
MODULE_NAME 		= algorithm.test
MODULE_INTRODUCE 	=
MODULE_TARGET 		= $(MODULE_NAME).app

# Depends
## Depend Module 
DEPEND_MODULE_LIST 		= ALGORITHM
DEPEND_MODULE_ALGORITHM_HOME 	= ${PROJECT_MODULES_HOME}/aqnote_algorithm
DEPEND_MODULE_ALGORITHM_LIB 	= aqnote_algorithm
DEPEND_MODULE_ALGORITHM_STATIC	= 1

# Compile
MODULE_LINK 	= c
# MODULE_BUILD 	= DEBUG

include ${PROJECT_MAKEFILE_HOME}/global.mk
