#
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20180809
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

# Constant
MODULE_NAME 		= algorithm.test
MODULE_INTRODUCE 	=

# Depends
## Depend Module 
MODULE_DEPENDS_PROJ 		= aqnote_algorithm

# Compile
MODULE_COMPILER 	= c
# MODULE_BUILD 		= DEBUG
MODULE_OUTPUT 		= $(MODULE_NAME).app

include ../../constant.makefile
include ${PROJECT_HOME}/global.makefile
