#     Title: 
#    Author: "Peng Li"<aqnote@qq.com>
#     CDate: 20181210
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#
SOURCE_DEBUG  	:= $(DEBUG)
SOURCE_TYPE 	:= c

## 说明：由于/opt/aqnote不是ld标准路径库，因此在运行时需要设置链接库路径
## 在环境变量中添加 `export LD_LIBRARY_PATH=/opt/aqnote/lib`，这样才能运行
LIBRARY_HOME 	:= /opt/aqnote
LIBRARY_FILE 	:= json-c
LIBRARY_PKG  	:= 

include ../../main.makefile



