#
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20180809
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

# Constant
MODULE_NAME 		= aqnote.test
MODULE_INTRODUCE 	= swap函数的几种实现
MODULE_TARGET 		= $(MODULE_NAME).app

# Depends
## Depend System
DEPEND_STD 	= pthread


# Compile
MODULE_LINK 	= cpp
# MODULE_BUILD 		= DEBUG

include ../../mk/config.mk
include ${PROJECT_MAKEFILE_HOME}/global.mk
