
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20190325
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

include ../../makefile.d/config.makefile

# Constant
MODULE_NAME 		= thread.threadpool
MODULE_INTRODUCE 	= 线程池

# Depends
DEPEND_MODULE 	=
DEPEND_PKG		=
DEPEND_NONSTD 	=
DEPEND_STD		= pthread

# Compile
MODULE_LINK 	=
MODULE_BUILD 		= DEBUG
MODULE_OUTPUT 		= $(MODULE_NAME).app

include ${PROJECT_MAKEFILE_HOME}/global.makefile
