
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20190325
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

include ../../mk/config.mk

# Constant
MODULE_NAME 		= thread.threadpool
MODULE_INTRODUCE 	= 线程池

# Depends
DEPEND_MODULE_LIST 	=
DEPEND_THIRD_LIST	=
DEPEND_NONSTD_LIST 	=
DEPEND_PKG			=
DEPEND_STD			= pthread

# Compile
MODULE_LINK 	=
MODULE_BUILD 		= DEBUG
MODULE_TARGET 		= $(MODULE_NAME).app

include ${PROJECT_MAKEFILE_HOME}/global.mk
