
include ../../mk/config.mk

# Constant
MODULE_NAME 		= aqnote_mmb
MODULE_INTRODUCE 	=
MODULE_TARGET 		= lib$(MODULE_NAME).a lib$(MODULE_NAME).so

# Depends
DEPEND_MODULE_LIST 		=
DEPEND_PKG			=

# Compile
MODULE_LINK 	= cpp
# MODULE_BUILD 	= DEBUG

include ${PROJECT_MAKEFILE_HOME}/global.mk