
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20190325
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

# Constant
MODULE_NAME 		= thread.lifecycle
MODULE_INTRODUCE 	= 线程生命周期

# Depends
DEPEND_MODULE_LIST 		=
DEPEND_NONSTD 		=
DEPEND_PKG			=
DEPEND_STD			= pthread

# Compile
MODULE_LINK 	=
MODULE_BUILD 		= DEBUG
MODULE_OUTPUT 		= $(MODULE_NAME).app

include ../../mk/config.mk
include ${PROJECT_MAKEFILE_HOME}/global.mk
