
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20190325
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

# Constant
MODULE_NAME 		= thread.lifecycle
MODULE_INTRODUCE 	= 线程生命周期

# Depends
MODULE_DEPENDS_PROJ 		=
MODULE_DEPENDS_PKG			=
MODULE_DEPENDS_NONSTD_PATH 	=
MODULE_DEPENDS_NONSTD_FILE	= pthread

# Compile
MODULE_COMPILER 	=
MODULE_BUILD 		= DEBUG
MODULE_OUTPUT 		= $(MODULE_NAME).app

include ../../constant.makefile
include ${PROJECT_HOME}/global.makefile
