
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20190325
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

# Constant
MODULE_NAME 		= kernel.mmap
MODULE_INTRODUCE 	=

# Depends
DEPEND_MODULE_LIST 		=
DEPEND_NONSTD 		=
DEPEND_PKG			=

# Compile
MODULE_LINK 		= c
MODULE_BUILD 		= DEBUG
MODULE_TARGET 		= $(MODULE_NAME).app

include ../../mk/config.mk
include ${PROJECT_MAKEFILE_HOME}/global.mk
