#
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20180809
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

# Constant
MODULE_NAME 		= gst.0x01
MODULE_INTRODUCE 	=

# Depends
DEPEND_MODULE 		= 
DEPEND_NONSTD 		=
DEPEND_PKG			= gstreamer-1.0

# Compile
MODULE_LINK 		= c
# MODULE_BUILD 		= DEBUG
MODULE_OUTPUT 		= $(MODULE_NAME).app

include ../../makefile.d/config.makefile
include ${PROJECT_MAKEFILE_HOME}/global.makefile
