#
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20180809
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

# Constant
MODULE_NAME 		= gst.0x01
MODULE_INTRODUCE 	=

# Depends
MODULE_DEPENDS_PROJ 		= 
MODULE_DEPENDS_PKG			= gstreamer-1.0
MODULE_DEPENDS_NONSTD_PATH 	=
MODULE_DEPENDS_NONSTD_FILE	=

# Compile
MODULE_COMPILER 	= c
# MODULE_BUILD 		= DEBUG
MODULE_OUTPUT 		= $(MODULE_NAME).app

include ../../constant.makefile
include ${PROJECT_HOME}/global.makefile
