#
#     Title: 
#    Author: "Peng Li"<aqnote@aqnote.com>
#     CDate: 20180809
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

# Constant
MODULE_NAME 		= gst.0x02
MODULE_INTRODUCE 	=

# Depends
DEPEND_MODULE_LIST 	=
DEPEND_THIRD_LIST	=
DEPEND_NONSTD_LIST 	=
DEPEND_PKG			= gstreamer-1.0
DEPEND_STD			=

# Compile
MODULE_LINK 		= c
# MODULE_BUILD 		= DEBUG
MODULE_TARGET 		= $(MODULE_NAME).app

include ../../mk/config.mk
include ${PROJECT_MAKEFILE_HOME}/global.mk
