
MODULE_NAME = demo
MODULE_TYPE = .app
MODULE_TYPES = app
MODULE_DEPENDS = moduleA moduleB
MODULE_BUILD = DEBUG

LIBRARY_HOME := 
LIBRARY_FILE := 
LIBRARY_PKG  := 

include ../../global.makefile

include ${PROJECT_HOME}/global.makefile
