#     Title: common used Makefile
#    Author: "Peng Li"<aqnote@qq.com>
#     CDate: 20180809
#     MDate:
# Copyright: http://aqnote.com/LICENSE
#
#

APP_DEBUG = $(DEBUG)
APP_HOME := /opt/aqnote
APP_LIBS :=  json-c
APP_PKG := 

include ../../main.makefile